# Vectorized

In [30]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [29]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc - tic)) + "ms")

249952.565179
Vecotrized version:2.0029544830322266ms
249952.565179
For loop:588.4158611297607ms


# Broadcasting in Python

In [31]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [32]:
cal = A.sum(axis = 0)
print(cal)

[  59.   239.   155.4   76.9]


In [33]:
percentage = 100 * A/cal.reshape(1, 4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [34]:
percentage = 100 * A/cal
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [37]:
a = np.array([1, 2, 3, 4])
print(a+100)

[101 102 103 104]


In [38]:
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([100, 200, 300])
print(b+c)

[[101 202 303]
 [104 205 306]]


In [41]:
d = np.array([[100], [200]])
print(b+d)

[[101 102 103]
 [204 205 206]]


# A note on python/numpy vectors

In [52]:
import numpy as np

a = np.random.rand(1, 5)

In [53]:
print(a)

[[ 0.45669672  0.923987    0.25078314  0.01436794  0.19060572]]


In [54]:
print(a.shape)

(1, 5)


In [55]:
print(a.T)

[[ 0.45669672]
 [ 0.923987  ]
 [ 0.25078314]
 [ 0.01436794]
 [ 0.19060572]]


In [56]:
print(np.dot(a, a.T))

[[ 1.16175304]]


In [57]:
a = np.random.randn(5, 1)
print(a)

[[ 0.21437768]
 [ 0.68251647]
 [-0.45846411]
 [ 0.9933492 ]
 [ 0.38505776]]


In [58]:
print(a.T)

[[ 0.21437768  0.68251647 -0.45846411  0.9933492   0.38505776]]


In [59]:
print(np.dot(a, a.T))

[[ 0.04595779  0.14631629 -0.09828447  0.21295189  0.08254779]
 [ 0.14631629  0.46582873 -0.31290931  0.67797719  0.26280826]
 [-0.09828447 -0.31290931  0.21018934 -0.45541496 -0.17653517]
 [ 0.21295189  0.67797719 -0.45541496  0.98674264  0.38249682]
 [ 0.08254779  0.26280826 -0.17653517  0.38249682  0.14826948]]


In [64]:
assert(a.shape == (5, 1))

In [67]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [77]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 0.31056394  0.3777041   0.46326879]
 [-0.28463099 -0.26821598 -0.06793459]
 [-1.04165634 -1.71967197  3.00806972]]
